version: '3'

services:
  proxy:
    image: traefik:v2.0
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dyn/
      - --certificatesresolvers.le.acme.email=jsweet@nd.edu
      - --certificatesresolvers.le.acme.storage=/data/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_vol:/data
    networks:
      landrs:
        aliases:
          - ld.landrs.org
  
  trifid:
    image: landrs/trifid
    build: ../trifid
    labels:
      - traefik.http.routers.trifid.rule=Host(`ld.landrs.org`)
      - traefik.http.routers.trifid.tls=true
      - traefik.http.routers.trifid.tls.certresolver=le
    networks:
      - landrs

  fuseki-geosparql:
    image: landrs/fuseki-geosparql
    build: ../fuseki
    command: -l false -u -rf "/geosparql_test.rdf>xml"
    volumes:
      - geosparql_vol:/jena-fuseki
    networks:
      - landrs

  data-cube:
    image: landrs/data-cube
    build: ../data-cube
    environment:
      BASE_URI: http://cube.landrs.org
      VUE_APP_API_URL: http://cube.landrs.org
      SPARQL_ENDPOINT: http://fuseki-geosparql:3030/ds/query
      SPARQL_UPDATE_ENDPOINT: http://fuseki-geosparql:3030/ds/update
      READ_MODEL_SPARQL_ENDPOINT: http://fuseki-geosparql:3030/ds/query
      READ_MODEL_SPARQL_UPDATE_ENDPOINT: http://fuseki-geosparql:3030/ds/update
      DEBUG: "*:error,dataCube:request,dataCube"
      STORAGE_FILESYSTEM_PATH: /uploads
      NODE_ENV: production
    labels:
      - traefik.http.routers.cube.rule=Host(`cube.landrs.org`)
      - traefik.http.services.cube.loadbalancer.server.port=8080
      - traefik.http.routers.trifid.tls=true
      - traefik.http.routers.trifid.tls.certresolver=le
    volumes:
      - data-cube_vol:/uploads
    networks:
      - landrs
      
volumes:
  geosparql_vol:
  traefik_vol:
  data-cube_vol:

networks:
  landrs:
    driver: bridge