version: '3'

services:
  proxy:
    image: traefik:v2.0
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dyn/
      - --certificatesresolvers.le.acme.email=jsweet@nd.edu
      - --certificatesresolvers.le.acme.storage=/data/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_vol:/data
    networks:
      landrs:
        aliases:
          - ld.landrs.org
  
  trifid:
    image: landrs/trifid
    build: ../trifid
    labels:
      - traefik.http.routers.trifid.rule=Host(`ld.landrs.org`)
      - traefik.http.routers.trifid.tls=true
      - traefik.http.routers.trifid.tls.certresolver=le
      - traefik.http.routers.trifid.tls.options=mintls
    networks:
      - landrs

  fuseki-geosparql:
    image: landrs/fuseki-geosparql
    build: ../fuseki
    command: -l false -u -rf "/geosparql_test.rdf>xml"
    volumes:
      - geosparql_vol:/jena-fuseki
    networks:
      - landrs
      
volumes:
  geosparql_vol:
  traefik_vol:

networks:
  landrs:
    driver: bridge