version: '3'

services:
  proxy:
    image: traefik:v2.0
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dyn/
      - --certificatesresolvers.le.acme.email=admin@example.com
      - --certificatesresolvers.le.acme.storage=/data/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_vol:/data
    networks:
      landrs:
        aliases:
          - ld.landrs.org
  
  trifid:
    image: landrs/trifid
    build: ../trifid
    labels:
      - traefik.http.routers.trifid.rule=Host(`ld.landrs.org`)
      - traefik.http.routers.trifid.priority=1
      - traefik.http.routers.trifid.tls=true
      - traefik.http.routers.trifid.tls.certresolver=le
    networks:
      - landrs

  fuseki-geosparql:
    image: landrs/fuseki-geosparql
    build: ../fuseki
    command: -l false -i -dg -v -u -rf "/base.ttl>ttl"
    volumes:
      - geosparql_vol:/jena-fuseki
    labels:
      - traefik.http.services.trifid.loadbalancer.server.port=3030
      - traefik.http.routers.trifid-query.rule=(Host(`ld.landrs.org`) && Path(`/query`))
      - traefik.http.routers.trifid-query.service=trifid@docker
      - traefik.http.routers.trifid-query.priority=2
      - traefik.http.routers.trifid-query.tls=true
      - traefik.http.routers.trifid-query.tls.certresolver=le
      - traefik.http.middlewares.trifid-query.replacepath.path=/ds
      - traefik.http.routers.trifid-query.middlewares=trifid-query
      - traefik.http.routers.trifid-update.rule=(Host(`ld.landrs.org`) && Path(`/update`))
      - traefik.http.routers.trifid-update.service=trifid@docker
      - traefik.http.routers.trifid-update.priority=3
      - traefik.http.routers.trifid-update.tls=true
      - traefik.http.routers.trifid-update.tls.certresolver=le
      - traefik.http.middlewares.trifid-update.replacepath.path=/ds/update
      - traefik.http.middlewares.trifid-update-auth.basicauth.users=admin:$$2y$$10$$qT00E87LP6o15pUSFNnirusP.DxUhpxE8lPBrxOgQMq7c9flvd.Vm
      - traefik.http.routers.trifid-update.middlewares=trifid-update,trifid-update-auth
    networks:
      - landrs

volumes:
  geosparql_vol:
  traefik_vol:

networks:
  landrs:
    driver: bridge